export default songs = [
	{
		id: 1,
		title: "Tim McGraw",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 1,
		playlist: "",
	},
	{
		id: 2,
		title: "Picture To Burn",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 2,
		playlist: "",
	},
	{
		id: 3,
		title: "Teardrops on my Guitar",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 3,
		playlist: "",
	},
	{
		id: 4,
		title: "A Place in this World",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 4,
		playlist: "",
	},
	{
		id: 5,
		title: "Cold As You",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 5,
		playlist: "",
	},
	{
		id: 6,
		title: "The Outside",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 6,
		playlist: "",
	},
	{
		id: 7,
		title: "Tied Together with a Smile",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 7,
		playlist: "",
	},
	{
		id: 8,
		title: "Stay Beautiful",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 8,
		playlist: "",
	},
	{
		id: 9,
		title: "Should've Said No",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 9,
		playlist: "",
	},
	{
		id: 10,
		title: "Mary's Song (Oh My My My)",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 10,
		playlist: "",
	},
	{
		id: 11,
		title: "Taylor Swift - Our Song",
		url: "[{},{},{}]",
		artist: "TaylorSwift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 11,
		playlist: "",
	},
	{
		id: 12,
		title: "I'm Only Me When I'm With You (Instrumental w/ BG vocals)",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 12,
		playlist: "",
	},
	{
		id: 13,
		title: "Invisible",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 13,
		playlist: "",
	},
	{
		id: 14,
		title: "A Perfectly Good Heart",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 14,
		playlist: "",
	},
	{
		id: 15,
		title: "Teardrops on My Guitar (Pop Version)",
		url: "[{},{},{}]",
		artist: "Taylor Swift",
		album: "Taylor Swift",
		"album-artist": "Taylor Swift",
		genre: "Country Pop",
		disk: 1,
		track: 15,
		playlist: "",
	},
];
